services:
  - type: web
    name: chat-with-ai
    env: python
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: HUGGING_FACE_API_KEY
        sync: false
